/**
 * 1°×1° world land mask (360×180, row 0 = 90°N, col 0 = 180°W), rasterized
 * from Natural Earth 1:50m land/countries (public domain, via world-atlas).
 * Cell values: 0 sea, 1 land, 2 United States, 3 Qatar. Run-length encoded:
 * each run is 2 base64url chars packing (value << 10) | (length - 1).
 */
const MASK_RLE =
  "P_P_D-QHEyQTAOQBAAQVEjQWAAQAADQnAAQAABQEBEQADNQGAIQKABQxA-QAAAQBAIQBAeQECmQWAHQtAdQBAAQAAAQCAAQFBCQG" +
  "CSQDADQEABQCABQDABQKADQyAfQCAAQDAAQBBNQECJQAACQCADQAAIQCABQAABQBABQBAAQCAHQAACQsAiQDACQAAAQABOQCCEQB" +
  "AAQAAGQAADQBABQCABQEAAQAAAQAAAQGAJQuBWQDAgQKCCQJAFQFABQEAAQFAVQmBMQEAaQXAWQEAAQBAAQABaQAAGQBANQAAIQA" +
  "AeQkBKQCAbQXAAQAB6QIAHQBACQDABQEACQBABQGAUQeAAQCBKQCARQBADQZACQCAAQEADQCAAQAALQCBbQFAAQIAAQCACQFAAQA" +
  "ADQDAAQDACQCATQdAAQBBKQBANQDABQAAAQAACQvALQEAhQBA1QCACQBAAQKAEQAACQBACQPAAQAAQQAAAQZAAQCBLQCALQDAAQB" +
  "ABQFAAQsACQAABQDAAQKAwgHABgAAkQIAGQDACQUANQBAAQVAAQAACQAAtQBAAQEAjQFAAQIAARLAkgVQBAFQAAAQEAAQAAAQBAD" +
  "QNAEQAAAQAAAQCAFQBADQAAAQIANQBAAQaAoQAAAQMAbQDADQEAARdACQGABQBALgYQaAAQAADQDAGQAABQCAAQBABQDAHQGANQY" +
  "AqQAAAQUAFQBAGQAAAQDAAQHAAQHAARqAKgWQfAAQLAAQGAAQFADQBACQHAJQUAwQYACQAACQXABRyAFgAADgSQ1ABQBAIQLAHQS" +
  "AvQTABQFACQZABRsACQDADgaQzAAQAAAQAAKQGABQBAJQMAPQAAAQHAZQJACQJAESLAFQBAKgTQ0ABQDADQBACQHANQKARQHAYQJ" +
  "ACQKABSLAKgBAIgTQxAEQBAMQBAAQCANQJAUQBAZQBAAQIABScAPgXQvAIQBADQAAHQBABQAANQHAvQLACSNABQLAAQAAOgYQuAP" +
  "QFAWQGAuQLAESGACQBABQIAVgMAAgCABgEQtAQQHAXQBApQAAFQMADQDAAQAAAR9AGQFAAQBAagHANgBQBgAQnAQQHAEQABEQEAA" +
  "QGAGQBAAR4AAQAAAQCAEQCAngCAAgAAOgCQoAOQJAAQDA5QBAIQCABQFAEQAAAR0ARQCAogAAAgCAPgCQnAPQOA2QEANQEAAQAAC" +
  "QAAARzAQQFAkgBAXgAAAgAQqAKQOA4QBAKQCABQDADR0ARQGA-gAAAgBQrAIQQA2QCAJQDAAQAAGRyATQFAggAAhQvABQVAxQCAA" +
  "QCAJQAACQAABQCAAR0ASQEBBQAABQvACQWAtQDACQCAGQAAASDAOQDBDQAACQtACQWAtQDABQFACSHAAQAAMQBBJRGAAQAAyQEAC" +
  "SIAAQAAMQBBJQAABRAACQAAyQAAFSJABQBBYQBAAQ4ACQBADQBAAQAAzQAAASLABQBBbQAgdQXAAQDAFQEAvSQABQABcgAAAgjQU" +
  "AIQAAAQAAySMACQABcgmQOgBQCAAQAABQAA5QgAAQDABQKADRUAEQABbgoQLgDQFA7QNAAQPACQBACQJAERTBigpQFgHABQBA-QM" +
  "ACQNAIQIACRVAFQABcgpQCgIA9QCACQIACQDACQLAKQHACRTAFQDBagoQCgIA9QLAFQAAAQCADQJANQFAERNAKQABcg0A9QKAKQC" +
  "ACQIADQDAEQHAERLBpgxBAQJAGQBAEQCAAQEAEQUACRDAAQGAKQBBdgxBAQIABQAAEQBAFQAACQCADQVADRBABQBABQCALQBBegv" +
  "AtQAASQIAPQAADQCABQWAEQ_AGQCALQBBfgtBCQHANQBAGQAADQVAERAAAQBAEQBAJQBBggtBFQAAFQJARQBAAQBABRUAFQBAGQE" +
  "BhgsBFQAADQLAYRTAFQCAEQFBigrBFQQAZRTAFQAADQCAAQBBogmBGQSAXRVAEQAACQDBsQBghBHQXAEQCALRVAJQABuQBAAQBgD" +
  "QBgYBGQZADQGAGRWAIQABwQAABQHgXBGQcAARkB7QBAAQHgAQBgFADgAAGgBBGQpAAQOACRGB7QAAAQLgCANgBBFQ6ACRGB6QCAA" +
  "QLgBANgCBCQuABQMADRDB9QBABQJgBAOgBBBQvABQNAGQ-B_QAABQLAPgABAQxABQMAAwAAGQGAAQ0B_QAACQJBSQxABQNADQBAJ" +
  "QyACQAB_QAABQIBRQzACQTAIQwACQACEQHANQAAAQDA9QzACQUAJQrAFQACFQGAIQAAIQBA7Q1ABQTAKQBAAQNAEQPABQACOQIAG" +
  "QCAJQBA6Q0ACQSANQNAFQNACQABcgAAxQIAEQDANQCA1Q0ADQQAOQLAIQLACQBCQQIABQAAAQCANQFAzQ1ACQPAPQKAJQLACQACU" +
  "QMBHQ2ACQMARQJALQLAMQBCKQKBHQ2ADQJATQIALQBABQJALQBCQQIBCQ4ACQIAVQFARQKAKQACSQIBBQ5ABQFAYQFARQKAKQBCU" +
  "QEBCQ6AAQDAbQEARQBAAQHAKQAAAQBCUQCBCQ7AJQAAUQEASQAABQGAOQACUQBAKQAABQAA1Q5AGQAAYQDASQAACQFAMQAAAQBCT" +
  "QCAGQDAAQEABQAAvQ6AAQFAYQDARQAAEQCALQACbQBABQAACQDAAQJAuRAAYQCAAQAAQQAAFQAALQAAFQACVQDABQRAuQ-AaQAAB" +
  "QAAQQBAWQCCYQAABQSAuQ9AdQBAQQAAXQCCbQSAuQNAAQsAeQBARQBANQBAFQBCcQXAqQJAEQrAtQAADQCALQDCjQYArQAAMQAAB" +
  "QmAvQBACQBAKQECjQZA8QkAxQBABQBAJQDCkQaA8QjAzQBABQBAGQGAJQACXQcA7QhA2QCAAQAAEQIAJQACWQcA7QhA3QDAFQIAC" +
  "QCADQACWQfA4QgA5QCAAQAADQIAIQAABQAAAQACRQbAAQCAAQCA1QgA6QCAFQGABQCAEQAADQBCQQeAAQDA2QeA7QFACQGABQCAN" +
  "QECJQpAxQcA9QDAIQAACQAAAQAADQAACQAABQKCGQqAxQaA_QCAdQICFQtAuQaBAQBAMQAANQAACQHABQAAAQBB_QsAuQaBCQCAY" +
  "QAADQIAGQAB7QsAvQZBDQFARQAAFQICFQrAvQZBLQFAAQBABQAAMQCACQBCFQpAwQaBOQAADQAAVQBAAQACCQpAxQZBtQACDQnAy" +
  "QZBZQAAAQAAIQAAJQACAQmAyQbAHQABQQFAEQAArQABfQkAzQbAGQBBPQFAFQBCLQkAyQcAGQBBLQBABQFAFQCCLQjAyQcAEQDBJ" +
  "QLAEQDCNQhAyQbADQFBIQOAAQAAAQDAVQAAKQAAdQABNQfAyQZAFQEBIQRAAQECPQdAzQYAGQEBIQXCPQdA0QVAIQEBHQaCNQdA0" +
  "QVAIQEAHQAA7QeAOQAB8QcA2QUAHQEBCQhAPQAB7QbA3QVAGQEBBQjCLQYA6QUAIQDBBQkCJQXA9QTAIQCBBQmCIQVA_QRALQABD" +
  "QmCHQVA_QRBPQnCHQWA-QRBQQnCGQVBAQPBSQmCGQUBCQNBTQlCGQVBCQNBTQlCGQTBFQLBVQkCHQSBFQKBWQJAHQRCHQMAAQEBG" +
  "QIBYQHAKQBAAQMCIQNAAQCBIQABfQCAPQAAAQNCHQPDCQLAWQABwQPDEQJAXQABuQQDEQJAYQABtQPDIQAAAQBAbQCBsQKDrQCBs" +
  "QLDsQBBsQIDRQCAXQBAAQABuQIDQQCAWQCBwQHDSQAAWQCBxQHDoQCBxQHDpQDBxQHDqQBBzQHFdQAAAQGFfQGCIQADWQFFiQEAI" +
  "QBFXQEFiQAAAQAABQAFjQAAAQDAcQAP_P_P_CRQAFgQAABQAFjQBChQADAQBBxQGAqQGADQDAJQBACQHAXQAB_QCBvQAABQLAVQ8" +
  "CUQBAAQABnQcAIRHCHQCAAQFBfQBAEQcAGRTCAQBAAQFBEQCABQGABQAAGQnADRXAAQAB7QEAAQEAxQCAAQGAARDACRjBZQCAWQD" +
  "ABQFAwROABRjA_QAAZQOADQBAAQAABQAAAQLAsS2A8QAACQAAHQFAAQBAJQmAqS0AAQAA1RMAqQAAAS0AyRMAoS_AmQGACRJAnTF" +
  "ABQCAiRHABQEAIQAAQQFAHTKAdQDAHRKADQBATQGAMS9AxRJAJQFAFQGANTBAjQBAFRZAWTKAtRZAGTcAZQGAAQAAAVJAPQIP_P_" +
  "Bf";

export const MASK_WIDTH = 360;
export const MASK_HEIGHT = 180;

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

let decoded: Uint8Array | null = null;

export function landMask(): Uint8Array {
  if (decoded) return decoded;
  const grid = new Uint8Array(MASK_WIDTH * MASK_HEIGHT);
  let p = 0;
  for (let i = 0; i < MASK_RLE.length; i += 2) {
    const packed = (ALPHABET.indexOf(MASK_RLE[i]) << 6) | ALPHABET.indexOf(MASK_RLE[i + 1]);
    const len = (packed & 1023) + 1;
    grid.fill(packed >> 10, p, p + len);
    p += len;
  }
  decoded = grid;
  return grid;
}

export function maskAt(latDeg: number, lonDeg: number): number {
  const row = Math.min(MASK_HEIGHT - 1, Math.max(0, Math.floor(90 - latDeg)));
  const col = (((Math.floor(lonDeg + 180) % MASK_WIDTH) + MASK_WIDTH) % MASK_WIDTH);
  return landMask()[row * MASK_WIDTH + col];
}
